on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'runner where this job will run'
        default: 'windows-cuda'
        required: false
      flav: 
        type: string
        description: 'flavour of the build: Windows/linux_x64/linux_arm64'
        default: 'WSL'
        required: false
      buildConf:
        type: string
        description: 'build configuration e.g. Release/Debug etc.'
        default: 'RelWithDebInfo'
        required: false
      is-selfhosted: 
        type: boolean
        description: 'self hosted runners do not need to use cache'
        default: true
        required: false
      skip-test: 
        type: boolean
        description: 'should test steps be skipped'
        default: false
        required: false
      cuda: 
        type: string
        description: 'ON/OFF based on this runner support cuda'
        default: 'ON'
        required: false
      prep-cmd:
        type: string
        description: 'commands required to be run on a builder to prep it for build'
        default: 'sudo apt-get update -qq && sudo apt-get -y install ca-certificates curl zip unzip tar  autoconf   automake  autopoint build-essential  flex git-core   libass-dev   libfreetype6-dev   libgnutls28-dev   libmp3lame-dev   libsdl2-dev   libtool   libsoup-gnome2.4-dev   libva-dev   libvdpau-dev   libvorbis-dev   libxcb1-dev   libxcb-shm0-dev   libxcb-xfixes0-dev   ninja-build   pkg-config   texinfo   wget   yasm   zlib1g-dev   nasm   gperf  bison python3 python3-pip dos2unix && pip3 install meson'
        required: false
      bootstrap-cmd:
        type: string
        description: 'commands required to boot strap builder after code checkout'
        default: './vcpkg/bootstrap-vcpkg.sh'
        required: false
      is-prep-phase:
        type: boolean
        description: 'this workflow is called for a prep phase: it will split vcpkg install into 2 portions to cache and save'
        default: false
        required: false
      cache-path:
        type: string
        description: 'the folder which needs to be cached e.g. .cache/vcpkg'
        default: ${{ '~/.cache/vcpkg/archives' }}
        required: false
      cmake-conf-cmd:
        type: string
        description: 'command needed for installing and configuring cmake'
        default: 'cmake -B . -DENABLE_WINDOWS=OFF -DENABLE_LINUX=ON ../base'
        required: false
      nProc:
        type: number
        description: 'number of threads to be used by cmake/make'
        default: 6
        required: false
      nTestTimeoutMins:
        type: number
        description: 'number of mins of timeout for tests run'
        default: 15
        required: false        
jobs:
  build:
    env:
      TEST_EXE: build/aprapipesut
      LD_LIB_PATH: '${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:/usr/local/cuda-10.2/compat/:/usr/local/cuda/lib64:$LD_LIBRARY_PATH'
      CMAKE_TC_FILE: '../vcpkg/scripts/buildsystems/vcpkg.cmake' # Note: naming this variable as CMAKE_TOOLCHAIN_FILE can cause havoc!!!
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Prepare WSL Image
      uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
    - name: Prepare builder
      run: |
        ${{ inputs.prep-cmd }} 
        apt purge cmake || true
        pip3 install cmake --upgrade
        nvcc --version || echo 'please install cuda and add /usr/local/cuda/bin into path'
        test -f /usr/local/cuda/include/cudnn.h || echo 'install cudnn as described in the readme.md'

      shell: wsl-bash {0}

    - name: Cleanup workspace on self hosted runners
      if: inputs.is-selfhosted
      run: 'Remove-Item -Recurse -Force *'
      shell: pwsh
      continue-on-error: true

    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        submodules: 'recursive' 
        lfs: true
        fetch-depth: 0
    - name: Checkout submodule
      run: |
        git submodule status > submodule_ver.txt
        cat submodule_ver.txt
        git rev-list --all --count 
    
    - name: Run VCPKG bootstrap
      run: ${{ inputs.bootstrap-cmd }}
      shell: wsl-bash {0}

    - name: Remove CUDA from vcpkg if we are in nocuda
      if: ${{ contains(inputs.cuda,'OFF')}} 
      working-directory: ${{github.workspace}}/base
      run: .\fix-vcpkg-json.ps1 -removeCUDA
      shell: pwsh

    - name: Remove OpenCV from vcpkg during prep phase
      if: inputs.is-prep-phase
      working-directory: ${{github.workspace}}/base
      run: .\fix-vcpkg-json.ps1 -removeOpenCV
      shell: pwsh

    - name: cache init on container build
      if: ${{ job.container != null }} # we are running on a container... move the cache "initially"
      run: |
        cp -R /root/.cache /github/home/ || true
        ls ${{ inputs.cache-path }} || true
        ls thirdparty/gst-build/gst-build-1.16/outInstall || true
      continue-on-error: true

    - name: Cache dependencies for fast cloud build
      if: ${{ !inputs.is-selfhosted }}
      id: cache-all
      uses: actions/cache@v2
      with:
          path: |
            ${{ inputs.cache-path }}
            ${{ github.workspace }}/thirdparty/gst-build/gst-build-1.16/outInstall/
            ${{ github.workspace }}/thirdparty/libmp4/build
          key:  ${{ inputs.flav }}-${{ hashFiles( 'base/vcpkg.json', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
          restore-keys: ${{ inputs.flav }}-

    - name: Build Gstreamer On Linux_x64 when it is not cached
      if: true # need to come up with proper clause to decide when this build should happen
      working-directory: ${{github.workspace}}/thirdparty
      run: |
        dos2unix ./build_gstreamer.sh
        ./build_gstreamer.sh
      shell: wsl-bash {0}
    
    - name: Build libmp4
      working-directory: ${{github.workspace}}/thirdparty/libmp4
      run: |
        dos2unix ./build.cmd
        ./build.cmd
      shell: wsl-bash {0}

    - name: Make build folder
      run: mkdir -p build
      continue-on-error: true

    - name: Configure CMake Common
      working-directory: ${{github.workspace}}/build
      run: '${{ inputs.cmake-conf-cmd }} -DCMAKE_TOOLCHAIN_FILE=${{env.CMAKE_TC_FILE}} -DCMAKE_BUILD_TYPE=${{inputs.buildConf}} -DENABLE_CUDA=${{inputs.cuda}}'
      shell: wsl-bash {0}      
      continue-on-error: ${{inputs.is-prep-phase}} # in prep phase we expect an error here due to missing OpenCV

    - name: Build
      if: ${{!inputs.is-prep-phase}}
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{inputs.buildConf}} -j ${{ inputs.nProc }}
      shell: wsl-bash {0}

    - name: List Test cases
      env:
        LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
      if: ${{!inputs.is-prep-phase}}
      run: ${{env.TEST_EXE}} --list_content > tests.txt
      shell: wsl-bash {0}
      timeout-minutes: 1
      
    - name: Run Tests
      if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
      env:
        LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all
      shell: wsl-bash {0}
      timeout-minutes: ${{ inputs.nTestTimeoutMins}}
    
    - name: Upload Test Results
      if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
      uses: actions/upload-artifact@v2
      with:
        name: TestResults_${{ inputs.flav }}
        path: |
          CI_test_result_${{inputs.flav}}.xml

    - name: Upload build logs 
      if:  ${{ failure() }} # only upload logs when we have a fialure above
      uses: actions/upload-artifact@v3
      with:
        name: BuildLogs_${{ inputs.flav }}
        path: |
          ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
          ${{ github.workspace }}/vcpkg/buildtrees/**/*.txt



