name: CI_Windows_x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  SUBMODS_TXT: submodule_ver.txt
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'false'
    
    - name: Checkout submodule
      run: git submodule update --init --recursive
          
    - name: Compute submodule status
      working-directory: ${{github.workspace}}
      run: (git submodule status > ${{env.SUBMODS_TXT}}) && (type ${{env.SUBMODS_TXT}}) && (echo $Env:LOCALAPPDATA)
      
    - name: Run VCPKG bootstrap
      working-directory: ${{github.workspace}}
      run: ./vcpkg/bootstrap-vcpkg.bat && ./vcpkg/vcpkg.exe integrate install
    
    - name: Cache VCPKG 
      id: cache-vcpkg
      uses: actions/cache@v2
      env:
        cache-name: cache-vcpkg
      with:
          # vcpkg cache files are stored in `~/.cache/vcpkg/archives` on Linux
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('base/vcpkg.json', 'base/CMakeLists.txt','vcpkg/baseline.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Cache gstreamer dependencies
      id: cache-gstreamer
      uses: actions/cache@v2
      with:
          path: ${{github.workspace}}\thirdparty\gst-build\gst-build-1.16\outInstall\
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('thirdparty/build_gstreamer.bat') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
  
    - name: Build gstreamer
      if: steps.cache-gstreamer.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}
      run: pip3 install ninja && pip3 install meson && cd thirdparty && ./build_gstreamer.bat && cd ..


    # - name: Configure CMake
    #   # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
    #   # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_WINDOWS=ON -DENABLE_LINUX=OFF -DENABLE_CUDA=OFF -A x64 ${{github.workspace}}/base -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
    
    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Test
    #   run:  ${{github.workspace}}/build/RelWithDebInfo/aprapipesut.exe --log_format=JUNIT --log_sink=CI_test_result_windows.xml
    
    # - name: Upload Test Results
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #    name: Unit Test Results
    #    path: |
    #      CI_test_result_windows.xml
  
    # - name: Upload all build logs
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: logs
    #     path: |
    #       ${{ github.workspace }}/vcpkg/buildtrees/*/*.log
    #       ${{ github.workspace }}/vcpkg/buildtrees/*/*.txt
    #       ${{ github.workspace }}/vcpkg/buildtrees/*/*/*.log
    #       ${{ github.workspace }}/vcpkg/buildtrees/*/*/*.txt

    
    # - name: Publish Unit Test Results
    #   uses: EnricoMi/publish-unit-test-result-action/composite@v1
    #   if: always()
    #   with:
    #     files: CI_test_result_windows.xml

  # event_file:
  #   name: "Event File"
  #   runs-on: windows-latest
  #   steps:
  #     - name: Upload
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Event File
  #         path: ${{ github.event_path }}
          
